[package]
name = "zed_devicetree"
version = "0.0.1"
edition = "2021"
publish = false
license = "0BSD"

[lib]
path = "src/devicetree.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.0.6"
